spring.application.name=yadot-api

# CONFIGURAÇÃO DA BASE DE DADOS
# spring.datasource.url=jdbc:postgresql://[HOST_DO_SUPABASE]:[PORTA]/postgres
# spring.datasource.username=postgres
# spring.datasource.password=[TUA_PASSWORD_DO_SUPABASE]
# spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURAÇÃO DO JPA / HIBERNATE
# Mostra o SQL no terminal (excelente para debug e para aprender o que acontece por baixo)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Como os teus colegas já estão a gerir as tabelas na BD, usamos 'none' ou 'validate'.
# 'validate' garante que as tuas classes Java correspondem às tabelas que eles criaram.
# NÃO uses 'update' ou 'create' em produção/projeto conjunto se não fores tu a gerir o SQL.
# spring.jpa.hibernate.ddl-auto=validate